apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared
  namespace: default
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: cloudflared
    creationPolicy: Owner
  data:
    - secretKey: CF_TUNNEL_TOKEN
      remoteRef:
        key: 67407087-8aa8-4419-96ab-b8ca5adff8c0
        property: password
