apiVersion: external-secrets.io/v1
kind: ExternalSecret

This directory contains Kubernetes manifests for deploying Prometheus and Grafana to monitor the MBO application.metadata:

  name: mbo-secrets

## Components  namespace: default

spec:

### Prometheus  refreshInterval: "5m"

- **Image**: `prom/prometheus:latest`  secretStoreRef:

- **Port**: 9090    kind: ClusterSecretStore

- **URL**: https://prometheus.hiibolt.com    name: bitwarden-login

- **Function**: Metrics collection and storage  target:

- **Retention**: 30 days    name: mbo-secrets

- **Storage**: NFS at `/meow/mbo/prometheus`    creationPolicy: Owner

  data:

### Grafana    - secretKey: dbn-key

- **Image**: `grafana/grafana:latest`      remoteRef:

- **Port**: 3000        key: ba011647-eac9-4a07-abf3-777090dac386

- **URL**: https://grafana.hiibolt.com        property: password

- **Function**: Metrics visualization and dashboards    - secretKey: grafana-password

- **Storage**: NFS at `/meow/mbo/grafana`      remoteRef:

- **Default User**: `admin`        key: <BITWARDEN_UUID_FOR_GRAFANA>

- **Password**: Stored in `mbo-secrets` secret        property: password


## Metrics Collected

The MBO backend exposes Prometheus metrics at `/metrics`:

- `mbo_messages_processed_total` - Total messages processed
- `mbo_active_connections` - Current active SSE connections  
- `mbo_order_book_depth` - Current order book depth
- `mbo_messages_errors_total` - Total processing errors
- `mbo_order_book_apply_duration_seconds` - Order book apply latency histogram
- `mbo_http_request_duration_seconds` - HTTP request latency histogram

## Dashboards

### MBO Order Book Metrics
Pre-configured dashboard showing:
- Total messages processed
- Active SSE connections
- Order book depth
- Processing errors
- Message processing rate over time
- Active connections over time
- Order book apply latency (p50, p95, p99)
- HTTP request latency (p50, p95, p99)

The dashboard auto-refreshes every 5 seconds and shows the last 15 minutes of data by default.

## Deployment

### 1. Create NFS Directories

On your NFS server (192.168.1.215):

```bash
sudo mkdir -p /meow/mbo/prometheus /meow/mbo/grafana
sudo chmod 777 /meow/mbo/prometheus /meow/mbo/grafana
```

### 2. Add Grafana Password to Bitwarden

1. Create a new Bitwarden entry for "MBO Grafana Password"
2. Set a strong password
3. Copy the UUID
4. Update `external-secret.yaml` with the UUID (replace `<BITWARDEN_UUID_FOR_GRAFANA>`)

Or skip this step to use the default password "admin" (not recommended for production).

### 3. Deploy the Stack

```bash
# Apply configuration
kubectl apply -f prometheus-config.yaml
kubectl apply -f grafana-datasources.yaml
kubectl apply -f grafana-dashboards-provider.yaml
kubectl apply -f grafana-dashboard.yaml

# Deploy services
kubectl apply -f observability-deployment.yaml
kubectl apply -f observability-service.yaml
kubectl apply -f observability-httproute.yaml

# Update external secret if needed
kubectl apply -f external-secret.yaml
```

### 4. Verify Deployment

```bash
# Check pods
kubectl get pods -l app=prometheus
kubectl get pods -l app=grafana

# Check services
kubectl get svc prometheus grafana

# Check HTTPRoutes
kubectl get httproute prometheus grafana
```

### 5. Access the Dashboards

- **Prometheus**: https://prometheus.hiibolt.com
- **Grafana**: https://grafana.hiibolt.com
  - Username: `admin`
  - Password: From Bitwarden or default "admin"

## Configuration Files

### Core Manifests
- `prometheus-config.yaml` - Prometheus scrape configuration
- `grafana-datasources.yaml` - Grafana datasource configuration (points to Prometheus)
- `grafana-dashboards-provider.yaml` - Dashboard provisioning configuration
- `grafana-dashboard.yaml` - MBO metrics dashboard JSON
- `observability-deployment.yaml` - Prometheus and Grafana deployments
- `observability-service.yaml` - Services for Prometheus and Grafana
- `observability-httproute.yaml` - HTTP routes for external access

### Related Files
- `external-secret.yaml` - Includes Grafana admin password from Bitwarden

## Customization

### Adjust Prometheus Retention

Edit `observability-deployment.yaml`:

```yaml
args:
  - '--storage.tsdb.retention.time=90d'  # Change from 30d to 90d
```

### Add More Scrape Targets

Edit `prometheus-config.yaml`:

```yaml
scrape_configs:
  - job_name: 'my-service'
    static_configs:
      - targets: ['my-service:port']
```

### Modify Dashboard

The dashboard can be edited in Grafana's UI. Changes will be saved to the Grafana NFS storage but won't update the ConfigMap. To persist changes:

1. Export the dashboard JSON from Grafana
2. Update `grafana-dashboard.yaml` with the new JSON (indented 4 spaces)
3. Reapply: `kubectl apply -f grafana-dashboard.yaml`
4. Restart Grafana: `kubectl rollout restart deployment/grafana`

## Troubleshooting

### Prometheus Can't Scrape Metrics

Check if the backend is exposing metrics:

```bash
kubectl exec -n default debug-shell -- curl http://mbo-reverse-proxy/metrics
```

### Grafana Can't Connect to Prometheus

Check Prometheus service:

```bash
kubectl exec -n default -it deployment/grafana -- wget -O- http://prometheus:9090/-/healthy
```

### Dashboard Not Showing Data

1. Check Prometheus is scraping successfully:
   - Go to https://prometheus.hiibolt.com/targets
   - Verify mbo-backend target is "UP"

2. Check Grafana datasource:
   - Go to Configuration → Data Sources in Grafana
   - Click "Test" on the Prometheus datasource

3. Check metrics are being exported:
   ```bash
   kubectl logs -f deployment/mbo-backend | grep metrics
   ```

### NFS Mount Issues

Check pod events:

```bash
kubectl describe pod -l app=prometheus
kubectl describe pod -l app=grafana
```

Verify NFS directories exist and have correct permissions:

```bash
kubectl exec -n default debug-shell -- ls -la /meow/mbo/
```

## Resource Usage

Default resource limits:

**Prometheus**:
- CPU: 250m request, 1 CPU limit
- Memory: 256Mi request, 1Gi limit
- Storage: NFS (grows with retention period)

**Grafana**:
- CPU: 250m request, 1 CPU limit
- Memory: 128Mi request, 512Mi limit
- Storage: NFS (minimal, mostly config)

Adjust in `observability-deployment.yaml` based on your needs.

## Security Notes

- Prometheus and Grafana are exposed via HTTPRoutes (internal gateway)
- Default Grafana password should be changed via Bitwarden
- Consider adding authentication to Prometheus if needed
- Both services are ClusterIP (not directly exposed outside cluster)
- Access controlled through your gateway/ingress configuration
