apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: default
  labels:
    app: mbo-grafana
data:
  prometheus.yml: |
    apiVersion: 1

    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://mbo-prometheus:9090
        isDefault: true
        editable: false
        jsonData:
          timeInterval: "5s"
