apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: grafana-admin
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        admin-user: admin
        admin-password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: 4c908dc2-191c-4a49-b1fa-cd32879feffb
        property: password
