apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-nfs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.4.38
    path: /mnt/meow/grafana
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-nfs
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: grafana-nfs
  resources:
    requests:
      storage: 5Gi
