apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: monikai-openai-api-key
  namespace: default
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: monikai-openai-api-key
    creationPolicy: Owner
  data:
    - secretKey: MONIKAI_OPENAI_API_KEY
      remoteRef:
        key: 9fdaf2ab-140e-40a2-b778-3ae2b8f31702
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: monikai-notion-api-key
  namespace: default
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: monikai-notion-api-key
    creationPolicy: Owner
  data:
    - secretKey: MONIKAI_NOTION_API_KEY
      remoteRef:
        key: d5442eaf-0eb7-4d98-a61b-4b2f6b80aa6e
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: monikai-discord-token
  namespace: default
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: monikai-discord-token
    creationPolicy: Owner
  data:
    - secretKey: MONIKAI_DISCORD_TOKEN
      remoteRef:
        key: a12cfb69-de6e-4ffd-83c8-ca3716f4f96d
        property: password