apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homelab-manifest
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/hiibolt/kubernetes-configs.git
        revision: HEAD
        directories:
          - path: nuclearbomb/*/*
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/hiibolt/kubernetes-configs.git
        path: '{{.path.path}}'
        targetRevision: HEAD
      destination:
        server: "https://kubernetes.default.svc"
        namespace: '{{index .path.segments 1}}'
      syncPolicy: 
        automated: null