apiVersion: cert-manager.io/v1beta1
kind: Certificate
metadata:
  name: argocd-server-tls
  namespace: argocd
spec:
  secretName: argocd-server-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  commonName: 'argocd.hiibolt.com'
  dnsNames:
    - 'argocd.hiibolt.com'
