apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: operator-oauth
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: 4946de34-cd05-48c8-96dd-d1a6d7bf189b
        property: username
    - secretKey: client_secret
      remoteRef:
        key: 4946de34-cd05-48c8-96dd-d1a6d7bf189b
        property: password
