apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hiibolt-pkcs12-secret
  namespace: certificate
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: hiibolt-pkcs12
    creationPolicy: Owner
  data:
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 5e096f22-4cb6-4eab-a61d-eddaf989681b
        property: password
