apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: degine-database
  namespace: default
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: degine-database
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: 686f13b5-b7df-42a1-8d73-62fe3eb447bf
        property: password
