apiVersion: v1
kind: Service
metadata:
  name: hermes
  namespace: default
spec:
  selector:
    app: hermes
  ports:
    - name: dashboard
      port: 9119
      targetPort: 9119
    - name: a2a
      port: 9900
      targetPort: 9900
    - name: a2a-sayori
      port: 9901
      targetPort: 9901
    - name: api
      port: 8642
      targetPort: 8642
