apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hiibolt-pkcs12
  namespace: certificate
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubernetes-secrets
  target:
    name: hiibolt-pkcs12
    creationPolicy: Owner
  data:
    - secretKey: tls.crt
      remoteRef:
        key: hiibolt
        property: tls.crt
    - secretKey: tls.key
      remoteRef:
        key: hiibolt
        property: tls.key
    - secretKey: keystore.p12
      remoteRef:
        key: hiibolt
        property: keystore.p12
    - secretKey: password
      remoteRef:
        key: hiibolt-pkcs12-secret
        property: password
