apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-gateway-to-certificate
  namespace: certificate
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: gateway
  to:
    - group: ""
      kind: Secret
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-external-secret-to-cert-manager
  namespace: certificate
spec:
  from:
    - group: external-secrets.io
      kind: ExternalSecret
      namespace: certificate
  to:
    - group: ""
      kind: Secret
